=== NCIP/cagrid/cagrid/Software/core/caGrid/projects/grape/schema/grape-target-grid-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.cagrid.org/1/grape-target-grid-configuration"
    attributeFormDefault="qualified"
    elementFormDefault="qualified"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:grape="http://www.cagrid.org/1/grape-target-grid-configuration">
    
	<xsd:element name="TargetGridsConfiguration" type="grape:TargetGridsConfiguration"></xsd:element>
	
	<xsd:complexType name="TargetGridsConfiguration">
		<xsd:sequence>
			<xsd:element name="activeGrid" minOccurs="1" maxOccurs="1" type="xsd:string" />
			<xsd:element name="lastUpdated" minOccurs="1" maxOccurs="1" type="xsd:date" />
			<xsd:element name="grid" type="grape:grid" minOccurs="1" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="grid" type="grape:grid"></xsd:element>
	
	<xsd:complexType name="grid">
		<xsd:sequence>
			<xsd:element name="DisplayName" minOccurs="1" maxOccurs="1"
				type="xsd:string" />
			<xsd:element name="SystemName" minOccurs="1" maxOccurs="1"
				type="xsd:string" />
			<xsd:element name="IvySettings" minOccurs="0" maxOccurs="1"
				type="xsd:string" />
			<xsd:element name="publicationDate" minOccurs="0" maxOccurs="1" type="xsd:date" />
			<xsd:element name="version" minOccurs="0" maxOccurs="1" type="xsd:string" />

		</xsd:sequence>
	</xsd:complexType>
	
</xsd:schema>

=== NCIP/cagrid/cagrid/Software/core/caGrid/projects/gaards-ui/resources/configuration/target-grid-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<TargetGridsConfiguration
	xmlns="http://www.cagrid.org/1/grape-target-grid-configuration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cagrid.org/1/grape-target-grid-configuration file://Users/jgeorge/Documents/Workspaces/caGrid-trunk/cagrid/projects/grape/schema/grape-target-grid-configuration.xsd">
	<lastUpdated>2009-10-08</lastUpdated>
	<activeGrid>training-1.3</activeGrid>
	<grid>
		<SystemName>training-1.3</SystemName>
		<DisplayName>Training Grid v1.3</DisplayName>
		<IvySettings>default</IvySettings>
		<!--
		<uri>http://software.cagrid.org/repository-1.3.0.1/caGrid/target_grid/training-1.3</uri>
		<DorianConfigurationFile>dorian-services-configuration.xml</DorianConfigurationFile>
		<AuthenticationServicesConfigurationFile>authentication-services-configuration.xml</AuthenticationServicesConfigurationFile>
		<DelegationServicesConfigurationFile>cds-services-configuration.xml</DelegationServicesConfigurationFile>
		<GridTrustServicesConfigurationFile>gts-services-configuration.xml</GridTrustServicesConfigurationFile>
		<GridGrouperServicesConfigurationFile>gridgrouper-services-configuration.xml</GridGrouperServicesConfigurationFile>
		<certificatesDirectory>certificates</certificatesDirectory>
		-->
	</grid>
	<grid>
		<SystemName>nci_prod-1.3</SystemName>
		<DisplayName>NCI Production Grid v1.3</DisplayName>
		<IvySettings>default</IvySettings>
		<!--
		<uri>http://software.cagrid.org/repository-1.3.0.1/caGrid/target_grid/nci_prod-1.3</uri>
		<DorianConfigurationFile>dorian-services-configuration.xml</DorianConfigurationFile>
		<AuthenticationServicesConfigurationFile>authentication-services-configuration.xml</AuthenticationServicesConfigurationFile>
		<DelegationServicesConfigurationFile>cds-services-configuration.xml</DelegationServicesConfigurationFile>
		<GridTrustServicesConfigurationFile>gts-services-configuration.xml</GridTrustServicesConfigurationFile>
		<GridGrouperServicesConfigurationFile>gridgrouper-services-configuration.xml</GridGrouperServicesConfigurationFile>
		<certificatesDirectory>certificates</certificatesDirectory>
		-->
	</grid>	
</TargetGridsConfiguration>
